Allow specifying initial metrics
felixge/httpsnoop pull request #18
Opened 2022-04-14 10:12 UTC by mitar

Fixes #17.

This preserves backwards compatibility and opens doors to other interesting use cases (where you can call `CaptureMetrics` multiple times, for example). I am not sure why would that be useful, but it looked like a nice generalization, allowing to specify initial values, not just status.

2022-04-14 12:26 UTC, felixge requested changes
LGTM, nice solution!

Only one change request: Could you update the godoc comments to mention the behavior difference between the APIs?

2022-04-15 20:34 UTC, mitar commented
Done.

2022-04-24 14:48 UTC, merged

2022-04-24 14:51 UTC, felixge commented
Thanks. Sorry for the late merge.

2022-04-29 07:47 UTC, mitar commented
Thanks for merging!

2022-04-29 07:48 UTC, mitar commented
BTW, maybe it is time for a new release?

2022-05-08 18:50 UTC, felixge commented
https://github.com/felixge/httpsnoop/releases/tag/v1.0.3 :)

2022-05-08 20:45 UTC, mitar commented
Awesome!